### ISSUE TITLE
[Question] How to specify qsub options within rules

### ISSUE THREAD

**Issue by linoferreira** [drjbarker/snakemake-gridengine#3]
I wanted to ask a question about how to set different SGE options for each rule in my Snakefile.

For example, suppose I want each of my rules to have a different job name when submitted. If I were submitting these jobs directly, I would use the `-N` option of the `qsub` command.

With Snakemake I know that one way to do this is to specify it in the `cluster.yaml` file. For instance, if the name of a rule in my Snakefile is `run_test` and I would like the `qsub` job to have the name `testing`, I can add the following to `cluster.yaml` after the `__default__` settings:
```
"run_test":
  name: "testing"
```
I was wondering if it would be possible to specify options like this in the Snakefile instead? I'm particularly interested in specifying different `-pe` options for different rules directly in the Snakefile rather than through the `cluster.yaml` file.

I have tried this:
```
rule run_test:
    input: ...
    output: ...
    resources:
        name='testing'
    shell: ...
```
but get the following error: `KeyError: 'Unknown SGE option or resource: name'`. I'm not sure what I'm doing wrong?

Thank you very much for your time and for making this code available!

**Comment by drjbarker** [comment]
My error message is not very useful here, but there's a comment I wrote a few lines above the error which was a good reminder to myself for this one!

https://github.com/drjbarker/snakemake-gridengine/blob/c1e51d617b6af7245bc0f3118c7854fe69f22672/sge-submit.py#L134-L136

As far as I'm aware (and I may be wrong or it may have changed since I wrote the wrapper), the values in the 'resources' section of a snakemake file can only be integers. So you cannot give 'name' a string here.

However, that is unrelated to the error you are seeing. We're calling a generic function for parsing through the option and resource maps, but for resources in the snakemake file I explicitly prohibit requesting options because in my interpretation of the snakemake ethos the resources section should only be used for requesting resources, not setting miscellaneous settings.

https://github.com/drjbarker/snakemake-gridengine/blob/c1e51d617b6af7245bc0f3118c7854fe69f22672/sge-submit.py#L223-L226

Probably I should catch after this line and raise a more useful error message and also check that resource requests are integers in the first place.

I agree that it would be nice to have a way to do what you want. Actually, I would like to set the job names from the rule names, but it seem to be hard/impossible to access that from the wrapper.

**Comment by linoferreira** [comment]
Thank you very much for the quick and detailed reply.

I had seen the comment that resources can only be integers but thought that might not apply to options. It all makes sense, though, and as you say options are not really resources and so shouldn't be specified in the same way.

Since what I was trying to do doesn't seem possible I'll try to close the issue now.

Thank you again for your time and for making this profile available, it's very useful!
